apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: generic-provider
  namespace: flux-system
spec:
  type: generic
  channel: general
  secretRef:
    name: webhook-address
