apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: postgresql
    namespace: bite
spec:
    releaseName: postgresql
    chart:
        spec:
            chart: postgresql
            sourceRef:
                kind: HelmRepository
                name: bitnami
                namespace: flux-system
    interval: 5m
    install:
        remediation:
            retries: 3
