apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pihole-webpassword
  namespace: pihole
spec:
  encryptedData:
    password: AgB5aZo77ZhHrbP0g4+7cbCH+i5230/rZY84DZcfIdGUtT35LeLx1b+SaDBXgcfpd4oPA6BepLgtD415rKGgkgY+V69N06BY6XcKKcFoL/ckSgYJlVkj+T4rYL/FlP5LWqN+fWot1auE1+aHk5oiN7hr6FZ1CW+/s4NU09nsKIyg8M3adac6sfldQ8wdTGH9epxWq/PNKZBmJF/Mh7/uLesTds3m3V8TvR7hMaeWr5U0GUVXdyU7aTOw5+x2NcpN8S1Pmdd7duvp1OCVmJ+mXtJ2CAxIOwNT42BMFW0L0iVZUUYCmTCJMD8srkFiySKDQtjlqnmsKX8v+2sRlRRbee+DrXQ5T6xLiYtSYC+wAaEghAGKeLDRkjTeELl/U0ViXtsPNqC9NyTc8PHDodIOS9A4joGak+ggci+SfLtGdubrQPiEfRo47V8MIIaXQK8X4DE9KTpqaeaDOQ6r1yfH4xjb8GRnvoapV9PPtkKokWChvAQmJyrVctE6OPVtoPahHh9D2flJ27tj21xsPqiErA4mlRH39AsONLJHhEzelvBkRYLkfH2j1Egcp3SoGkyvMQBI1jzgwoQZfeemHxkhYcNST6QvUurabTWxz0i0EVKOy2S81kfZM0ZeqRpWQrTR/K1a+GolmTEoDx3g9z2wLppnQsFWfCSm9sj1upZ5Hprzt2T/MeIVEkBbSRhivVA/sIRPXV3jpidwD61eDVuhzyohFCpmz8bmI/sV81m3ylkzdzZCuxRrjFLK
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: pihole-webpassword
      namespace: pihole

