apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
    creationTimestamp: null
    name: pihole-webpassword
    namespace: pihole
spec:
    encryptedData:
        password: AgAxutY9Jto5DsNtqT+rxob65Ry/ukEJAvHBv2GmjDx/Y1HzB5JVl8eNm5lwq1aYa82+/PnDYmxoWfN/OayGvCyvtfNNBFafpEv8z4T0EmlmftVPeMIKjnVmKktQqorGtAlFI71AY7cDoqcjKqdJoQVM3Sa71uLNCfCf9fC3aGIuBf96azThzaH87QJ2JjtpbV5TtdCGZ/bL9iSd6CX5erYrBZIvNcOZapMwxuFIMLLS8JxiN3+C8yVi63vlx0drpMlyhCcCljqhImBSeskRvW/NFkeSVruWEsk7yFbWynkvJSTIt5xK7zr+4f2jMODGmqtWde3odkiVAIX34i5m71bbhGdRVuEKI16WMYeyqX/Xksba6YIAzlTqnWWuIAq9Poz10oJm66hPp5bD2oAug+I/T+//j4FMB5vWqcf8Xv5w7/lnS2YEfo0lJz5xFjzsiNHkAd2gzNOm7ISNkhfzMntQAOK00MbZSypFmpkCvxZwGjPtJ4m+3BN0HMB2hY21HIrvnXbmD/DnUXP8GBMNcO7YN29XqP6O72WCa5Q5Nj6YNIDDMDFA6Uq28RFXCD/XlhgD1cG54yRKHuO7Bhk8s3T/CGocRN1hZheuZwbMH8s6w1ryJ2xjc3Ylebk+zNS7cuzxONIy65hvE9D5KhN/bnUeWr/uXzuFD7+yevfNcnHN8/Ato0TcxRqdOPY4PGJO2yvKsif7ZSbQwEnKQRIfaPeLp3oaPzLql20nsciD1+Cb2P7Est7srMRE
    template:
        metadata:
            creationTimestamp: null
            name: pihole-webpassword
            namespace: pihole
