apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImagePolicy
metadata:
    name: bite
    # namespace: bite
spec:
    imageRepositoryRef:
        name: bite
    filterTags:
        pattern: "^[0-9]*$"
    policy:
        numerical:
            order: asc
