apiVersion: apps/v1
kind: Deployment
metadata:
  name: bite
  # namespace: bite
spec:
  replicas: 1
  strategy:
    type: Recreate
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: bite
  template:
    metadata:
      name: bite
      labels:
        app: bite
    spec:
      containers:
        - name: bite
          image: ghcr.io/martijnjanssen/bite:242
          imagePullPolicy: IfNotPresent
          env:
            - name: BITE_PORT
              value: "5051"
            - name: BITE_DBHOST
              value: "51.158.129.251"
            - name: BITE_DBPORT
              value: "62149"
            - name: BITE_DBNAME
              value: bite
            - name: BITE_DBUSER
              value: bite
            - name: BITE_DBPASSWORD
              valueFrom:
                secretKeyRef:
                  key: postgresql-password
                  name: postgres-password
            - name: BITE_SENDINBLUEKEY
              valueFrom:
                secretKeyRef:
                  key: sendinbluekey
                  name: sendinblue-secret
            - name: BITE_MAILCALLBACKURL
              value: https://links.biteapp.nl
            - name: BITE_AWS_SESSIONREGION
              value: eu-central-1
            - name: BITE_AWS_RECIPESIMAGESBUCKETNAME
              value: bite-production-recipes-images
            - name: BITE_AWS_PROFILESIMAGESBUCKETNAME
              value: bite-production-profiles-images
            - name: BITE_AWS_STORIESIMAGESBUCKETNAME
              value: bite-production-stories-images
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: access-key-id
                  name: aws-access
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: secret-access-key
                  name: aws-access
            - name: BITE_GOOGLE_SERVICEACCOUNTJSON
              valueFrom:
                secretKeyRef:
                  key: serviceaccountjson
                  name: google-serviceaccountjson
            - name: BITE_GOOGLE_FIREBASESERVICEACCOUNTJSON
              valueFrom:
                secretKeyRef:
                  key: firebaseserviceaccountjson
                  name: google-firebaseserviceaccountjson
            - name: BITE_APPLE_APPSHAREDSECRET
              valueFrom:
                secretKeyRef:
                  key: appsharedsecret
                  name: apple-appsharedsecret
          # ports:
          #   - containerPort: 5051
          #     protocol: TCP
          #   - containerPort: 5081
          #     protocol: TCP
          # livenessProbe:
          #   failureThreshold: 3
          #   httpGet:
          #     path: /api/v1/management/health
          #     port: 8080
          #     scheme: HTTP
          #   initialDelaySeconds: 60
          #   periodSeconds: 20
          #   successThreshold: 1
          #   timeoutSeconds: 1
          # readinessProbe:
          #   failureThreshold: 5
          #   httpGet:
          #     path: /api/v1/management/health
          #     port: 8080
          #     scheme: HTTP
          #   initialDelaySeconds: 60
          #   periodSeconds: 5
          #   successThreshold: 1
          #   timeoutSeconds: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bite-frontend
  # namespace: bite
spec:
  replicas: 1
  strategy:
    type: Recreate
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: bite-frontend
  template:
    metadata:
      name: bite-frontend
      labels:
        app: bite-frontend
    spec:
      containers:
        - name: bite-frontend
          image: ghcr.io/martijnjanssen/bite-frontend:242
          imagePullPolicy: IfNotPresent
