apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImageRepository
metadata:
    name: bite
    # namespace: bite
spec:
    image: ghcr.io/martijnjanssen/bite
    interval: 1m0s
    secretRef:
        name: ghcr-cred
