apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bite
  annotations:
    ingress.kubernetes.io/protocol: h2c
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: grpc.bite.martijnj.nl
      http:
        paths:
          - backend:
              service:
                name: bite-grpc
                port:
                  number: 80
            path: /
            pathType: ImplementationSpecific
    - host: web.bite.martijnj.nl
      http:
        paths:
          - backend:
              service:
                name: bite-web
                port:
                  number: 80
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - grpc.bite.martijnj.nl
        - web.bite.martijnj.nl
      secretName: bite-martijnj-nl-tls
