apiVersion: apps/v1
kind: Deployment
metadata:
  name: bite
  # namespace: bite
spec:
  replicas: 1
  strategy:
    type: Recreate
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: bite
  template:
    metadata:
      name: bite
      labels:
        app: bite
    spec:
      containers:
        - name: bite
          image: ghcr.io/martijnjanssen/bite:12
          imagePullPolicy: IfNotPresent
          env:
            - name: BITE_PORT
              value: "5051"
            - name: BITE_DBHOST
              value: postgresql
            - name: BITE_DBPORT
              value: "5432"
            - name: BITE_DBNAME
              value: bite
            - name: BITE_DBUSER
              value: bite
            - name: BITE_DBPASSWORD
              valueFrom:
                secretKeyRef:
                  key: postgresql-password
                  name: postgres-password
            - name: BITE_SENDINBLUEKEY
              valueFrom:
                secretKeyRef:
                  key: sendinbluekey
                  name: sendinblue-secret
            - name: BITE_MAILCALLBACKURL
              value: https://web.bite.martijnj.nl
          # ports:
          #   - containerPort: 5051
          #     protocol: TCP
          #   - containerPort: 5081
          #     protocol: TCP
          # livenessProbe:
          #   failureThreshold: 3
          #   httpGet:
          #     path: /api/v1/management/health
          #     port: 8080
          #     scheme: HTTP
          #   initialDelaySeconds: 60
          #   periodSeconds: 20
          #   successThreshold: 1
          #   timeoutSeconds: 1
          # readinessProbe:
          #   failureThreshold: 5
          #   httpGet:
          #     path: /api/v1/management/health
          #     port: 8080
          #     scheme: HTTP
          #   initialDelaySeconds: 60
          #   periodSeconds: 5
          #   successThreshold: 1
          #   timeoutSeconds: 1
