apiVersion: v1
kind: Service
metadata:
    name: bite
    namespace: bite
    labels:
        app: bite
spec:
    type: LoadBalancer
    loadBalancerIP: 192.168.1.3
    ports:
        - port: 80
          protocol: TCP
          targetPort: 5051
    selector:
        app: bite
