apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bite
  # annotations:
  # kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: grpc.bite.martijnj.nl
      http:
        paths:
          - backend:
              service:
                name: bite
                port:
                  number: 80
            path: /
            pathType: ImplementationSpecific
    - host: web.bite.martijnj.nl
      http:
        paths:
          - backend:
              service:
                name: bite
                port:
                  number: 81
            path: /
            pathType: ImplementationSpecific
