apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImageRepository
metadata:
    name: bite
    namespace: flux-system
spec:
    image: ghcr.io/martijnjanssen/bite
    interval: 1m0s
    secretRef:
        name: ghcr-cred
