apiVersion: v1
kind: Service
metadata:
  name: bite-grpc
  labels:
    app: bite
spec:
  type: LoadBalancer
  ports:
    - name: grpc
      port: 80
      protocol: TCP
      targetPort: 5051
  selector:
    app: bite
---
apiVersion: v1
kind: Service
metadata:
  name: bite-web
  labels:
    app: bite
spec:
  type: LoadBalancer
  ports:
    - name: web
      port: 80
      protocol: TCP
      targetPort: 5081
  selector:
    app: bite
