apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  creationTimestamp: null
  name: bite-grpc
spec:
  routes:
    - kind: Rule
      match: Host(`grpc.bite.martijnj.nl`) && PathPrefix(`/`)
      services:
        - kind: Service
          name: bite-grpc
          port: 80
          scheme: h2c
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  creationTimestamp: null
  name: bite-http
spec:
  routes:
    - kind: Rule
      match: Host(`http.bite.martijnj.nl`) && PathPrefix(`/`)
      middlewares:
        - name: ssl-redirect
      services:
        - kind: Service
          name: bite-http
          port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  creationTimestamp: null
  name: bite-frontend
spec:
  routes:
    - kind: Rule
      match: (Host(`bite.martijnj.nl`)) && PathPrefix(`/`)
      middlewares:
        - name: ssl-redirect
      services:
        - kind: Service
          name: bite-frontend
          port: 80
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - bite.martijnj.nl
      secretName: bite-martijnj-nl-tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bite-site
  annotations:
    kubernetes.io/ingress.class: traefik
    ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  routes:
    - kind: Rule
      match: (Host(`biteapp.nl`)) && PathPrefix(`/`)
      middlewares:
        - name: ssl-redirect
      services:
        - kind: Service
          name: bite-site
          port: 80
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - biteapp.nl
      secretName: biteapp-nl-tls
