apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  creationTimestamp: null
  name: bite-links
spec:
  routes:
    - kind: Rule
      match: Host(`links.biteapp.nl`) && PathPrefix(`/`)
      middlewares:
        - name: ssl-redirect
      services:
        - kind: Service
          name: bite-frontend
          port: 80
