apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bite
resources:
  - ../../base/bite
  - ./secrets
  - namespace.yaml
  - bite-links-ingress.yaml
images:
  - name: ghcr.io/martijnjanssen/bite
    newName: ghcr.io/martijnjanssen/bite
    newTag: "578" # {"$imagepolicy": "flux-system:bite:tag"}
  - name: ghcr.io/martijnjanssen/bite-frontend
    newName: ghcr.io/martijnjanssen/bite-frontend
    newTag: "580" # {"$imagepolicy": "flux-system:bite-frontend:tag"}
