apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bite
resources:
    - ../../base/bite
    # - ./secrets
    - namespace.yaml
patchesStrategicMerge:
    - postgresql-values.yaml
