apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bite
resources:
  - ../../base/bite
  - ./secrets
  - namespace.yaml
  - bite-links-ingress.yaml
  - bite-staging-prod-temp.yaml # TEMP STAGING TO PROD REDIRECTION
