apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: bite
  namespace: flux-system
spec:
  image: ghcr.io/martijnjanssen/bite
  interval: 1m0s
  secretRef:
    name: ghcr-cred
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageRepository
metadata:
  name: bite-frontend
  namespace: flux-system
spec:
  image: ghcr.io/martijnjanssen/bite-frontend
  interval: 1m0s
  secretRef:
    name: ghcr-cred
