apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImagePolicy
metadata:
    name: bite
    namespace: flux-system
spec:
    imageRepositoryRef:
        name: bite
    filterTags:
        pattern: "^[0-9]*$"
    policy:
        numerical:
            order: asc
