apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: bite
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: bite
  filterTags:
    pattern: "^[0-9]*$"
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: bite-frontend
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: bite-frontend
  filterTags:
    pattern: "^[0-9]*$"
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: bite-site
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: bite-site
  filterTags:
    pattern: "^[0-9]*$"
  policy:
    numerical:
      order: asc
