apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImageRepository
metadata:
  name: webhook-proxy
  namespace: flux-system
spec:
  image: ghcr.io/martijnjanssen/webhook-proxy
  interval: 1m0s
  secretRef:
    name: ghcr-cred
