apiVersion: image.toolkit.fluxcd.io/v1alpha2
kind: ImagePolicy
metadata:
  name: webhook-proxy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: webhook-proxy
  filterTags:
    pattern: "^[0-9]*$"
  policy:
    numerical:
      order: asc
