apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: apple-appsharedsecret
  namespace: bite
spec:
  encryptedData:
    appsharedsecret: AgBjh0w9vRCQ+fiMWd641tsya9dQATkKtGPqJvjp88JR15CsJB/+laTwlBZfjUjoaBlHlKtGsfipkYuQK7AiQPcKbhf539VMyCJZFrkGptAdhmrDkguL+3rW6455ZvBAV9KA1ykTyBNEOE8ZYVRDo91yrlD7d+OzjpfoSj0iEC/X4v+hkrpkh3rYibkzNPqgJwlz6MFsbU7wfmo0xRbaTL1Y6ANULBX18Qix6xb7F5rtOav2oKn7Ye6WooYmDo0VwLVz6Ce2skzjjY8lELdqICcxvorsyf9YQo4WvgK/n0LgMhQ7BwGodQ2uk8YMSE6tYU50Gc663xYXm/f9EswRx9iYFDeJDcLJDC2Eoivk1VS0Vl8jQAIu6cmcg91GEMALmqmWEe6FTT01iwUMbay0Y5Np7uvsfAo7qR3wTzEcPM9frk2kwhi45NqnNTv/PVkzKs45rhTj4oh8j189p+Ou6cqZ1cKkhztF8SwQzfmFyxFmXtvIda3AD1PnaOara3yR62Ax05X7tu8mqfWvbK2XOgzOLYQB5GYXxBoWYZgzrH/3bF5RtQVgJAR7Uab42T995DUp40/v7hvMXUSzGsrDV2vVGzPQ+f0xcSA1UrFk1GQqmwt3yOlXE5lyLcykd/oiDSQkU0FVom57bP1K6us1e69i20V7hieUmU0YBCogsKnjCI5VAPv5tjgP4I8nXZf83AkSfwGXQQ7V1/As/+nuIRRe1T1vkIATJ8Aqcp7qNB+TLpU=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: apple-appsharedsecret
      namespace: bite
    type: Opaque
