apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
    creationTimestamp: null
    name: ghcr-cred
    # namespace: bite
spec:
    encryptedData:
        .dockerconfigjson: AgA4XCbdC0AlT9iDp9VQm4do7uVyxFi7+sNDqNTbfzogWwN4JylmMDSaSPw2FgsYJ8pGwmYkWlZdgafqcssFNNPDqT0Su0sqDSTCoxrwZYWaQZIVPYOqqnZcxWtJnserLEx30fCp1yXjCHyQa79B69qkxfo0m0zCjk1IGEpsw00NRVw0ZV8G8mab9fg0aFsLS1oCVlh5K6jdXK33WXzRHNsnElHGYa0t5YATh9pnFy7Br0gRzZzN89pJkEn4W5WDuqqN1E4tFXeakiHvyAekXf/Z2autTJspqWnPbDFQg6srOo5lqaJUOrgni8+3SjZLrVeJetghyNpcldMoD0enNYzUnak+NfGPAr2c+Q06/AKBWaHdsQ5uVgKmCxeiFzZcv8C0G+dKvBjt2zVBUYhVTWy7C3qRFg/m2LgTVad6fQVromyPl5BZnv0E8N0sigJxC9lmi7Q6zLhhSNLvxMcgmi4z6GB/XTndEAEluxL8NOX07Qy3wuC+w4zKaOxFboF5zke5IAkVlJUnSWjD/Wtxeg9kFD6bKDtsr/PbVGKzCZvptpZOfJQziXTaXTfWI6R2ljcvQor/9cBsI/Mjrd85ccVrEMPZ6fahv+iscHFOWxqiqdXc2jsZJCKbw8ZfnhrN5GMhLZjmjWVe5xoxJtQSlvToUQemvXQK0R4i/4tEELf8XVbnWVtqUjXeeeGXbEjUYqoIXgD4vghwiP6GHHiv+cabYIQ04D+NF4GTF0cMc5oRF8YUbZYZYB9tBBbK4QhJKJBEfYj/X24hjggJNz+Y0U6mNdkKdCFFS9MVAf9iNZy1LYS6TqKtdm6CtdkXsJlF8pT06GkmkGKghbZ5XlY7lzqukMfLNxuQ0tYF4NzzpJoZ0ld53Yg1KsY6zMBWyhpVKCAKV5l5Itns4zN/OWiMN2aYH8jUoV6bT7AJjGzyUp/UEFmyMATELDfRmQf/wNSHOrWUhb4uj6GJwy25tnFp1Mzbp70sOHVWFEvmx2eQciTDmmk0pWX9Ig==
    template:
        data: null
        metadata:
            creationTimestamp: null
            name: ghcr-cred
            # namespace: bite
        type: kubernetes.io/dockerconfigjson
