apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bite
resources:
    # TODO: re-enable when reconciliation is fixed for `apps` folder
    # - ghcr-secret.yaml
    - postgresql-password.yaml
    - sendinblue-secret.yaml
    - aws-access.yaml
