apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-password
  namespace: bite
spec:
  encryptedData:
    postgresql-password: AgCWYuaMa8q5cB/NM8wlkvozB7KDuYJhIMwamI5x5eUMAYI9FV17wO1Yz7qH4c1Nb95N4Rpm58yyZIitIOeC1G3y835xsYJyLtyYfDNF9sogMFOOk2cjgkFUkKaVL7/mEduHlQuPoUGkjbGpZUcomlm8d9OLiBlNkYs3UJezkDrCxEB6MqnxfQRSQu5agO5rFkloJfKNbng4Yx+FmNdiENdwb2gC+BtafIXZTtZYFZB6RpD1JMU4HkHS1eT2ACwGDHJWjQ9FFF1hS8Kn5USDtjn7Cu0oJY5IAKPXP+Z4WLcOlcb43cJHO6ixMFtViDYxDFOZTXT62KEMYX0y0E8Hj2JJKt/yIBSH/Au3Ao5l/xcZ//LJvnO9dJaHHwrksgFRgroa8aVrBaADNgjm95NbcoB5dJssx9y7PMB+P/pEydTJPQXpqFb5Fg4GRNnZqKsbn8z4wG5lOrxpmSk/k0PGry00VnSrOyCvVHKDkv+BsjuQRaYJL9+1S9DK5ndtviM9giUg/kVPTfmkDNa/fOOKNSv6G+xzXTy3kF6+U2iguTWegdqzkLg/39VsH3HdqdPNLKYDNjGiPu/CHibfusu9oqp4nYwu3HyP2g1saMZQNs9uTqlPbQ2MRzbTZ9uQmnkH8FN7eJeW/CDjOXRLbKmn3KkKnMBTMgs+4K6ThfkkvGEvBIwHINAWotQfBQajdoybxJjtBJa0RW0tZCCQeQHDSxztAl/wIwSrYtno
    postgresql-postgres-password: AgBhqAUPKQgZoqQ+6upVv7jvUALokkNxm47MwPxN3nSlZIpdSILt6qYJgEK9runVM17XYeOjTqt624gTgDd9fkv1EeRAr55xBkezH6t629z868mpPkWvQSePf7gV00dQiKzCpvicuNjejDIxSDMbG/G5XwfPG7Wz+cZxDHaGxPpVikdzerwE55NzMV4hc0bljT//+fCP9Lk52a6iz9mtkAU+bMGTmxrvHM1qschhZCaBsWuc4t6SjwERreinV6c+1qPVLr8PXosJW0y/f3Ei4l+UwpEWM92DzyRWiqmwMLSYXkcwLV+VizYJIcdqTZkwNDHQCI4w/agi8jVoslAP/C/1a0deSLHMQ8vbzMS9G9YgbBcsk8XuAYadc491UevVDwJ985tlwEIpMLWFD2tqG8FMGUJbrulnSBUZQQRvaJUGEMDiO/QCTU9djw7dtKFNilIMQyUv064t98B3j3MLfHOxe4RQ5X02/okAy0ADm7whqQPhlB8awdE6IwxknjEwSkyfRuSW5eIPkULxlNR11ARiJbGdwiLv5q9PzMLYDbaKZW3kZtD161Fls1+kAwm65TOiXTzAZwzX1TohtmlLqLVG3aawR358ujw/AMctyvAWq1ldbF0Q11dbqdVniU/hf/O1YQqwkMCqTALOgAZ7jvfcfFfTZrXcC2O5JFe6271wO2JBmMXno6nQey02c6eivpL2Hy7Fx0hip3yVH4uDzPV7Y8srHmkfggn4
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: postgres-password
      namespace: bite

