apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: sendinblue-secret
  # namespace: bite
spec:
  encryptedData:
    sendinbluekey: AgBVWH8FNqQLfNFBm3ZCKt25ibf0/IQ4E6oXBKm9pOFSszwyC2+1IhJ4fdK0Nns8rIOLhA3PZz9uxkZFGaoPZafGyvSBHYfTgSZi4ShGqAvq9tj9fWxWbC3uOzq2pC/qBcXIDukQH6dFGlKzdd9ZfHKjsvbqOTLyh1xJmSgFuuWF/5TJ934wBm2rsEtGewmH4rBdE+0qyQKEr3bcY1VFCrUKVCdg9pya2ahNgC1OtxnMZV3xNkD03rO9+Ph3NwdktwF/8w1wc6M52KCCHxDLXet2o+RT3hcgoVORbHOq4c99VFvX0eIsDtYqUBO/pS086El0wfRDiGxcAOuZkNpW8FpJLFlVoDfzYbjNskXZxIAiZ6DxIh4q7pqFQsAgBMWCt93eFb2xUBqcrWQSkyUFWhaukizrqtJUHZsGJLblCGVwmpCBuXdO6V99utD4Kd6wMXSVcbJ6A9K9ttL0ODWgyHLLX9pWKefE0ZhuJ3qWTWiDRg7JuRHJTu4gl5X8olqUKFJ3NxJFsE0OKppHNI2wx00nWGOeP+o6t9UO2EKAFlUJwGQ48vdHGVT7GF+KSTrrURPZNE78Pg+82MMQyj9e+D3LkMVPEn9wnof2PtpoIFmnhyudf1aMz0G1MorhhaSfYNC38GvmMlErN/y0KxC6erMhiP86EbLRQgeJnsirXyD/YBMgfWo80HpfkYYUFU8Ddfu4otR3YZQRvxtBrrk9UQqiIdpBhaeV2cqJnk60AIpcQyteyQIanTXGpdK4Tb6JvIMm6GdySbgIgTZGnpcE6De3NYvgDh2ItOuFPdIjFlYbl7Hy4vIgsM92MA==
  template:
    metadata:
      creationTimestamp: null
      name: sendinblue-secret
      namespace: bite
