apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
  namespace: pihole
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      name: pihole
      labels:
        app: pihole
    spec:
      containers:
        - name: pihole
          image: pihole/pihole:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: Europe/Amsterdam
          volumeMounts:
            - mountPath: /etc/pihole
              name: pihole-config
          ports:
            - containerPort: 80
              name: http-web
      volumes:
        - name: pihole-config
          persistentVolumeClaim:
            claimName: pihole-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-dns
  namespace: pihole
  labels:
    app: pihole
spec:
  type: LoadBalancer
  selector:
    app: pihole
  ports:
    - name: dns-udp
      port: 53
      protocol: UDP
      targetPort: 53
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: 53
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-web
  namespace: pihole
  labels:
    app: pihole
spec:
  type: LoadBalancer
  selector:
    app: pihole
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http-web
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pihole
  namespace: pihole
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls.certresolver: acmecertresolver
spec:
  rules:
    - host: pihole.martijnj.nl
      http:
        paths:
          - backend:
              service:
                name: pihole-web
                port:
                  number: 80
            path: /
            pathType: ImplementationSpecific
    - host: pihole.home
      http:
        paths:
          - backend:
              service:
                name: pihole-web
                port:
                  number: 80
            path: /
            pathType: ImplementationSpecific
---
# Redirect to https
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: https-redirect
  namespace: pihole
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pihole-redirect
  namespace: pihole
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: pihole-https-redirect@kubernetescrd
spec:
  rules:
    - host: pihole.martijnj.nl
      http:
        paths:
          - backend:
              service:
                name: pihole
                port:
                  number: 80
            path: /
            pathType: ImplementationSpecific
    - host: pihole.home
      http:
        paths:
          - backend:
              service:
                name: pihole
                port:
                  number: 80
            path: /
            pathType: ImplementationSpecific
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-pvc
  namespace: pihole
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
