apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-address
  namespace: flux-system
spec:
  encryptedData:
    address: AgBT0Wz7JrE2oCQ1UiNItT8hnBn24r3FeLo2SJH9uuzyvZLAsmEL9EzsHvSCnWNXAUiGs26b8sShlUOFsjsz7RrCM+P8YvR8eSSsRnkQu252TXLRyuQGZCzOg4gLGwCX1ZkRFqnKHRi82zBroCsN7ytWW8iyPtrJpDPYSWAGqFJ4uPot6WriRo0sPOLGt80GoyBXnne3ojvvIQHwJBD3v64oY9OQMZsm2YflMlHagredggmofCHEQrdMqTCjOjFIa3rQ5qXqxWAddlzBu33V0yCOPWAURMLb1tR+ijg085s+9azj+0UQDCA57xepD0nF6Jjm5+CNswPfcXdQndRbdE5dwO7zs8+NXdxX39XC6Yf3oTAj4mIwPKD9EK8RzP0VKiHGN1hwl8mh39CnIQor7QVYmtQBf/t6U2bXe69rO//8hWMyzFufRCG7Gv0kUv36vHW/4JTYDoeR5xTkovC/AV7CkhA3ECmRYEA9vpkMxE/Lm8i28JlEVBeDORX/LdKvPwQSS87R3JDEVaOkkjTI85BlTEskPeAy2jmCZoshRQQISrTI+td0oVcr2IgULQ4Sru1qbMI5Fq+jBfXEp7WK2JzN2+5kl2PUkE/WGfWRp+PoIFOov6LXDwLMgUK+CfCJzkQv9FNb9JiBmAiwAyPPHSUP2u6jXZ3RNIuO2jLtx98ezsVbnoRzryel9R6/o4yTxpS352GdeGiXDQW3w+4OZeWaUTmw0nCOQZYWctZhSJBLtIh+W+ihgnMDaYW0GdQtIotY4WorT9DWSHjoVH4K1Rmtm4k=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: webhook-address
      namespace: flux-system
