apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-address
  namespace: flux-system
spec:
  encryptedData:
    address: AgAYCKTyXyTRi0RzsxNz2u4uTBeRxBP9zZVC2ZTXIHQd1D/qAC1m/qtTfiegiuEGRFgdPKi03KVg8WINeoPHVWLJOpWGKRbVQ1VsDiVN+FpMH+sjem7I9XlgNXObUt2iPwiShc9SwMXjJEY1MelTHbLPJbSzWeJMIrN4Uz1MgRFrFY/f0cmtoBoMxc006nzOqlc0Qi4LAWyq6aobYkoe9pv+CX6aHjHAcevvpBmB9Li5KjzS9q5enPGXBODHyPHJAlY9ge8kh65QYIVR4Xh/7vocQcJ8u6IypkuZIgX/1LBq8Ao7h69gJIT43fCo5TnE03AujIjuFZ3n0vGOH6Q+ahR/8GZzWtlo4IsAzotHSQfnYFjzlf6Y4KTmXGqUjTqu8Ll9A7bea00VrqV1MZZbBlvRGlfTTws6hBjNJllUh1uGXJn3QwFNTZ3+t4FF0rdSGclMwllau+nvfD283zrNrYrMQ5i9T2w5mSwhvRIxfiE3btLcuvbWx9fHVDml9tyNKrE47BY5ztQvA7YmdLnNdu0AAH/3kjhXtKpLvVXY/xx3FX6tiSOOyBx71vRKgyA+ft0PcJcBqx5RMh+oUKxYDGaJy78xPkr3nK3Q4uH7hpeHOgLlWGUMYzD1xjJEzhH6gIr4NS2LR/iB7zBMDnbnxHEJnTxwyjATjqx21H4GEiGdQ9UaRVrOwYJLniZu2n4CPcNN7PCm3Jt2wadmYMeeMg+RMOQC5yVoVW9p0wxxzgENfROwKN9LUh4hMvdqZv4=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: webhook-address
      namespace: flux-system

