apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImagePolicy
metadata:
    name: bite
    namespace: flux-system
spec:
    imageRepositoryRef:
        name: bite
    policy:
        numerical:
            order: asc
