apiVersion: apps/v1
kind: Deployment
metadata:
  name: bite
spec:
  template:
    spec:
      containers:
        - name: bite
          env:
            - name: BITE_PROFILE
              value: "dev"
            - name: BITE_MAILCALLBACKURL
              value: https://web.staging.bite.martijnj.nl
            - name: BITE_DBPASSWORD
              valueFrom:
                secretKeyRef:
                  key: postgresql-password
                  name: staging-postgres-password
            - name: BITE_SENDINBLUEKEY
              valueFrom:
                secretKeyRef:
                  key: sendinbluekey
                  name: staging-sendinblue-secret
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bite-grpc
spec:
  rules:
    - host: grpc.staging.bite.martijnj.nl
      http:
        paths:
          - backend:
              service:
                name: bite-grpc
                port:
                  number: 80
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - grpc.staging.bite.martijnj.nl
      secretName: grpc-staging-bite-martijnj-nl-tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bite-web
spec:
  rules:
    - host: web.staging.bite.martijnj.nl
      http:
        paths:
          - backend:
              service:
                name: bite-web
                port:
                  number: 80
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - web.staging.bite.martijnj.nl
      secretName: web-staging-bite-martijnj-nl-tls
