apiVersion: apps/v1
kind: Deployment
metadata:
  name: bite
spec:
  template:
    spec:
      containers:
        - name: bite
          env:
            - name: BITE_PROFILE
              value: "dev"
            - name: BITE_MAILCALLBACKURL
              value: https://staging.bite.martijnj.nl
            - name: BITE_DBPASSWORD
              valueFrom:
                secretKeyRef:
                  key: postgresql-password
                  name: staging-postgres-password
            - name: BITE_SENDINBLUEKEY
              valueFrom:
                secretKeyRef:
                  key: sendinbluekey
                  name: staging-sendinblue-secret
            - name: BITE_AWS_BUCKETNAME
              value: bite-staging-recipes-images
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  key: access-key-id
                  name: staging-aws-access
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: secret-access-key
                  name: staging-aws-access
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bite-grpc
spec:
  rules:
    - host: grpc.staging.bite.martijnj.nl
      http:
        paths:
          - backend:
              service:
                name: bite-grpc
                port:
                  number: 80
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - grpc.staging.bite.martijnj.nl
      secretName: grpc-staging-bite-martijnj-nl-tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bite-http
spec:
  rules:
    - host: http.staging.bite.martijnj.nl
      http:
        paths:
          - backend:
              service:
                name: bite-http
                port:
                  number: 80
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - http.staging.bite.martijnj.nl
      secretName: http-staging-bite-martijnj-nl-tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bite-frontend
spec:
  rules:
    - host: staging.bite.martijnj.nl
      http:
        paths:
          - backend:
              service:
                name: bite-frontend
                port:
                  number: 80
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - staging.bite.martijnj.nl
      secretName: staging-bite-martijnj-nl-tls
