apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging-bite
resources:
    - ../../base/bite
    - ./secrets
    - namespace.yaml
patchesStrategicMerge:
    - bite-values.yaml
    - postgresql-values.yaml
