apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging-bite
resources:
  - ../../base/bite
  - ./secrets
  - namespace.yaml
  - postgresql.yaml
patchesStrategicMerge:
  - bite-values.yaml
images:
  - name: ghcr.io/martijnjanssen/bite
    newName: ghcr.io/martijnjanssen/bite
    newTag: "440" # {"$imagepolicy": "flux-system:bite:tag"}
  - name: ghcr.io/martijnjanssen/bite-frontend
    newName: ghcr.io/martijnjanssen/bite-frontend
    newTag: "443" # {"$imagepolicy": "flux-system:bite-frontend:tag"}
