apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - ../base/podinfo
    - ../base/pihole
    - ../base/bite
patchesStrategicMerge:
    - podinfo-values.yaml
    - pihole-values.yaml
    - postgresql-values.yaml
