apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/podinfo
  - ../base/pihole
  - ./bite
  - ./webhook-proxy
  - ./secrets
patchesStrategicMerge:
  - podinfo-values.yaml
  - pihole-values.yaml
images:
  - name: ghcr.io/martijnjanssen/webhook-proxy
    newName: ghcr.io/martijnjanssen/webhook-proxy
    newTag: "5" # {"$imagepolicy": "flux-system:webhook-proxy:tag"}
