apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: pihole
    namespace: pihole
spec:
    chart:
        spec:
            version: ">=1.0.0"
    values:
        ingress:
            hosts:
                - pihole.martijnj.nl
        DNS1: "1.1.1.1"
        DNS2: "1.0.0.1"
        adminPassword: ""
        serviceDns:
            loadBalancerIP: 192.168.1.3
            # annotations:
            # metallb.universe.tf/allow-shared-ip: pihole-svc
            type: LoadBalancer
