apiVersion: apps/v1
kind: Deployment
metadata:
    name: pihole
    namespace: pihole
spec:
    replicas: 1
    template:
        metadata:
            labels:
                app: pihole
                name: pihole
        spec:
            containers:
                - name: pihole
                  image: pihole/pihole:latest
                  imagePullPolicy: Always
                  env:
                      - name: TZ
                        value: "Europe/Amsterdam"
