apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: podinfo
    namespace: podinfo
spec:
    chart:
        spec:
            version: "6.x.x"
    values:
        ingress:
            annotations:
                ingress.kubernetes.io/ssl-redirect: "true"
                kubernetes.io/ingress.class: traefik
                cert-manager.io/cluster-issuer: letsencrypt-prod
            tls:
                - hosts:
                      - podinfo.martijnj.nl
                  secretName: podinfo-martijnj-nl-tls
            hosts:
                - host: podinfo.martijnj.nl
                  paths:
                      - path: /
                        pathType: ImplementationSpecific
