apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: postgresql
    namespace: bite
spec:
    chart:
        spec:
            version: ">=1.0.0"
    values:
        postgresqlUsername: biteUser
        postgresqlPassword: testing
        postgresqlDatabase: bite
        persistence:
            size: 1Gi
        initdbScripts:
            init-01.sh: |
                #!/bin/bash
                export PGPASSWORD=$POSTGRESQL_PASSWORD
                psql -U postgres bite -c "CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\";"
