apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: postgresql
    namespace: bite
spec:
    chart:
        spec:
            version: ">=1.0.0"
    values:
        postgresqlDatabase: bite
