apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: cert-manager
spec:
    releaseName: cert-manager
    chart:
        spec:
            chart: cert-manager
            sourceRef:
                kind: HelmRepository
                name: jetstack
                namespace: flux-system
            version: "1.2.0"
    interval: 1h0m0s
    install:
        remediation:
            retries: 3
    # Default values
    # https://github.com/bitnami/charts/blob/master/bitnami/nginx-ingress-controller/values.yaml
    # values:
    #     service:
    #         type: NodePort
