apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: pihole
    namespace: pihole
spec:
    releaseName: pihole
    chart:
        spec:
            chart: pihole
            sourceRef:
                kind: HelmRepository
                name: pihole
                namespace: flux-system
    interval: 5m
    install:
        remediation:
            retries: 3
    # Default values
    # https://github.com/stefanprodan/podinfo/blob/master/charts/podinfo/values.yaml
    values:
        ingress:
            enabled: true
            annotations:
                kubernetes.io/ingress.class: traefik
