---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: telegram-access
  namespace: homelab
spec:
  encryptedData:
    chat-id: AgAKxgpzTXQ97BTFGxJVZ+6YjgPWk3uyEFfRRLld1LGEuTtQlTKdyehRKLo+7SY01R9CHOSnUiU+8cEAugO4rBtDMRRYySMudnhLOuJWzYQxk6IerIWTg0E8T93B5Jl0hu+x3IDPGvEZD6//gKhSkQiXLGCUcFkY3yvQuD0Qv2pkdlZnqQA3KDqOlhZXkr9M/WIgtaLNhBt8Jy+Pned+anyNNuilp8ZYEdS/IhEQIOZluw5WsS1wnuLSjMxB8HjLoHGPiL2eOvaT8cjTce4Nkzbxs9ZsAyLgUDZLYQZK4fWZvcTb/mF/R07iX1QkqeeYyNBXmuJfuB+MfY4T/KtgsWSztS+oepBLpECP6GQK8JJ5/b73ej/PwYXL118wQF5XXu+/CkG9L2UcKKZ1/r6n8ifxZz/+NU2g6XuTcl9uj0SHMXi5ZAZM+nh8VgWgui5xH5Tj0BmQiXkmZTo4kEgQJpF7zB+PSiET3ObyE4eHW2KpIzoPo+8H/urdu03s+UQWV6TfKtIUjc37hPrIFqX5MI0slJmiFOKZwB3tHzZ512gZ4RYNOaNY3NdGnauIgIkmuptm5bWV2bFeSdCSOE+rSSLjXQXSjuhTbWeR+JyZYp420vwd6xTpXewcqVyCRFmjqCwyq9cqZPQtlqlKFxotirt1ehJ4M1ENhOKfo+ua4TI8PVMCS1cjasll/Ahx+Jn+kmMiJbVxSCTxygE=
    token: AgAu2pvsd+g2e2PAD1dOJpx8awqrEttSOuhhQWZ6kfM5/v+vVhJ09PdttjlrluOg0HOD3TVYwIZ03UZFFVaVgWDDctVipIZAYC4YYwm7m+l3JqPyVXFhxL/jebyz2snNUPL8MRMqAULiHFEf17ZsqNLJhvH+EISg0XMDS7ty0p4dgo2KtrB1gWwCnIocZkI+TdQa4XI12QbLE4Ze7a/dKLU+bsT098OqO5RIuNKXsvds5BF6LJGwZG4fBi8HnAgXkyDwbtjVisNBQQuaJmOafM/eLofDSu8SwD3xj0hPZ0xa//mSZ98l0iSUd7oI3HmFRWSvSHHsRgEaCtOlN20nBcGm43/ZKNvQeU0Ji9/Ouxs/ztW02vgcwKjP22kog0IJJYOZZZli+RgHK9v+3cgop6C2w0934C25934KFzw8V35eR63VicK62s1XAhtzfgMkSaW3/VYIuBKpmBZ1djRDaFVHg3E4gUG/zM1xtMsf18WgNn664YKyvzjSYZqhdYcrvVzrWPwgkCv3jxjkLMl+tkg55mcnHVbxc7ovdFTIC9dHihEH8iXVOeG0LqKLHWWpCbgBAQaWFTIdOrlIdPCJfbfc5Kg/zNwxFp9YCjGpCa7GkNargJ8LQQiI9Fi/ClCS6PCvGPxGOI408NljXGzg+x4uh/TLpHEI/m8y1tkSKMqWLK027agAz/F2A/6VsjqLkkOzuzvPbTM62+HMo/dbfv6VgEBM85YB4kHk6lxfrsjqtAJ2RDF7cjXgQQDY/vfT
  template:
    metadata:
      name: telegram-access
      namespace: homelab
