apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
    creationTimestamp: null
    name: pihole-password
    namespace: pihole
spec:
    encryptedData:
        password: AgAZLGgUm0ebJVIf0soj/04+dt2IJNofRb1CmBg19/VS2PdNSndEDhnH5vf7DSYFAmcRVamwldWBy3j/FrKS38ToCCRO81SBKFCO0D2btl+s9NepM0oBM37lxwVR7g/8p+oA7JP4jI6phi++Fzp9aDXfYFkFLGWk3rYbf3pCVSEbZhrKYxOVasqGXy/XUu52Spokx35OUQiZD6iDbUmJ/20gfKk3QVT2rWEYe53FUmXQ2O/Qa32sgzkELcfIOmpRgqzHkM2nuTe5IZ1B8+XAQJdSTfYYfMkBOLfX5INxJ27y46EnAmCrbBX2D6pIrD9LWVr8IUeWXA5IDvTQqKtidtv6puLvY2SjfHl/Wiq/g8EVuW22HRTc/HEh8Rm5k7D4UACPZb1j8/Pm2E9LwwL4MRli4yj3EKLELaztEbzwF9j4qAt5Yydr5KInjO/R7QO4CZtkzMaJ5OJlpY9qlg1qJHhVZ4eluS3hCeq15dFcwXq5X0jeIjrV9b9eGtyzsGlMTwT5sBOlkhwCW9obepixen1uDFrpBBEWQABiiL2CPSfA27stsUNUTvMC1VRy1P7fiKMn1kPfGqnM+DudihPmmsh5/or8I0pPCw30ZrjOqGsbkcqSnLXb9Ni0ezzbdQsf1e9U+RuJJBb36UVLGgwrpf+mObOkXaS1TH30YMxj1qb77OgmVlekTD5WmVkpW4r1bsQnUXS9sKxaHI6DfrjO0JXEwKeFtQYzL8CLpehShTrfq+vOT01qhKo+
    template:
        metadata:
            creationTimestamp: null
            name: pihole-password
            namespace: pihole
