apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-password
  namespace: bite
spec:
  encryptedData:
    postgresql-password: AgB6rpZeoKIMoCbyR9ZK/ayFQUYpxcxt6MLz/brp9kgJMOFBzwrfD3e9IMlJZyQA4T9JxElzF3uAEGiClUe0MKxM8Cef1lDIUiXXH6yTnU/slh3Bnnj9WxOTLvm6H5TbbNH2z1dJA9CnrEy/qwVGZY1rtjnDt6Y+au5uT8bebh4RqNPBojQq/OBnrvINDg1+yuLkFv3zWnNLNJQQ6Z+t6YUL689MKlx/sOQhIfFwkHk8jRWwSa3tjemYHDiTGaZ0wrxBNN+1EQAIGa9aV4nanph9C8Z+CBrXUoCm3bjEbJfw3s98LJMHyjjSL3W/Wk4ZnHFpS8ItYD5MDATWyBzS2VMdDNjc3+7pbxpKR1lxLXBQJO9oaFYF6rcyfw8/J5xpGNm0Z5NTA8HmOEPzghvBQ2dQFagYm6QUe13Dv5l30Cj4G4WdL74SJ+xKvvscWO9Qtc76wo8qopRsezhxDmGdqvodnSb3J+OXXRchETpCg4Rr3lKD0FtX7zow3eyJylS9RO/ZJPPXgxBk0gT5b4ipf5qeGHlaq7XP5QBXucIWCbwO6SmxKPe3+/r1odpKZuh9TDXqNE1ldYYs0h6G95EkjKmWi1/YUqoI0tNdPviE/S8jJw/GPrJInOF7RYi8Mn/0UMUGpkUr4cFlTPNx2El+AbLos6GG8QeKYrDVHErhKbu1G4c+GVB1uE7Xur0W/lTetBlJvGHKfgnDgiKZx3hW2CoC380v67lzZlst
    postgresql-postgres-password: AgB0vBI+mkBRDKfiMksDPifQJlQTrYcqSxnIlfPhIAW4qFZK9eKKgEJezM/fcXP6cTAsgfyiQ9v8VM/jTqYAj2lk2ceARlBh4HkACnDqjfPIw4lNwinldz0L2BVxks01aF4XydQ8UvXJhqtv6aG+kQ6BwRB+Os6/bA4GArLkwzRSw8XHASdr8JT8ULvlbI0u2J9i8IlE7cM1/7kbZ0ZoEDHob+PDr0WQOYRYk30rGxcCy2TRQ6ZdTiDL69edXRWvk0b4gE9Ni/VNCgiR3G8ChrCLfPSF3a/jsj0n1NQcW5bsKxxhGMDXeDXEYF4Ofgq9krInGxTE5C/G9uN/kvrHVLWS9dSedlDethKBtCTTDwJT4RbixFMkVxdghiAVJuw13tEL1eFEG/OpyHwYmrw1Up6ieEdrJU080Oe8vHTYGA0WvIR3N3ZU3KPn35AkPN7o2fk459/+wWCCGP1kz/aWY4rcGUFgrEyGJYFR0tEPSdlBVW0Gkb69eoivayNDnX6S/9uBLSL8+imxOMpGlKLYwbac5vFymrWKpBpJjsHnG0VAnKAyBLAX3R8FXDMJEdzyUNuluXxH9uGzh/XMUFRb1lkf9NfND0sry/QTx5eL22rE0DXIMa+3/6iSjbjatuZYhLFzL5boEDQ6s2Nke79Fhqm0rOaJqZQEd/CC1l84qIQ6/0CSJS3cU56pYex34HkO6FadezkYQ2WLGu5gCDjYpoX35UVnHomnjZcQ
  template:
    metadata:
      creationTimestamp: null
      name: postgres-password
      namespace: bite

