apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-cred
  namespace: flux-system
spec:
  encryptedData:
    .dockerconfigjson: AgCNaVVD1bodYu+E121BqRi7/pVFxUcU3GPNnNRln/XL2H5mx/eCdJc2JF2R03YT4e0CKzglBdKsvkO85McBVBQpl6I2XQtPrR2t01q1Kn3TAaldETnGYld6jhoRzHtIGWcxQa28vbxoAQeFv2sIIsFujVT6yUmMyOYhVwjj6sgCfOX652Pv+26v2oXyjaaqmiafyOwDIwXRSsNrL2la/rrSWK9PdK9LVg/v7JKq5h3Mrz3SUNEmU5kadVhfVtTEvBB/YLqapoOdV1VfwtJ9fqQUgdLXlMib4vkImSdu1y2b+VTUlJh0e68mysNxyHqJK3UykjCNMDNEOZ+T9zLJfw5bqeKZeV3e+IHWhF7GSVV0i+qx2ev8bPVFiPv0IOrIknQw/kAEt/ycisR7drOlhkNulWG6VBMLJspir+3bf1vjl29rcU+LpeLrWVsRFm28XjEXMrOpUTuqZ1kTlyH5V1A3kltmPdTMeWMe6hOC63MP5SSH7igSBl5C4fHf2EAFML+XazS/r6KEWKsPzI5Fne/rjyiuvSEGmbA6W+yLhyAnsaRdeDadEQ4bTfkDthzeaBepbSsU57pWt6vDh1ObJOcAS72DutPOSprVFqCShy80P9Y19OI4K0Vwmlk0mNBlj4EuOhi7pyEEW1nbiBiDRF+sYqS5cIbipFoZXwABtwboeUCzB10IO69CRNChh8AlBe9n8wAsnt09ofrLV7GBzXd9uNO3q2bULk9xHlkTZDAvJB94SyL6GI5bYslGUY485P4y1PZKngDe3ch2Htc1CbDqvklm80Rk+EWmBLea+vXq+H1x4GQGgurO3kkmNeA+56aGJ0NfF4yImEl8iHE/mbltMI74AoUUtQi5ShIobzdUf6EIfeLA9KZe3jnzMdEPOUODklYujgRo0f4Nr2bJ0j7reR60asqrmxrWqBOHk55a/Hl001Nbm1uvmIs+rFiHMwvFu4y2Zo7MVVI0wEGJ2DuH05Ii
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ghcr-cred
      namespace: flux-system
    type: kubernetes.io/dockerconfigjson
