apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-cred
  namespace: flux-system
spec:
  encryptedData:
    .dockerconfigjson: AgBVVKMyfdCkbcXtHvsAykBklQQ506ss6StswUV0SBc3mjrGjbYz2ZxhnGz2xjhNjqDPxhCZuoHsN7ek0v1mfntZ2+9XALcrxXDHjDsXJJmmdcrpKlQtm0lhXfS4R3qrjm1VTA7YUEhTGf9KIOanvUB9OKlvOCoN9SlhRonDjnx831QP47x+fmBofD08xIqjQi+vYRVWx2+p3Vzag9urkABeUQvaaqwSDrF6e1kNjebwYp5jEWApeR52IDVZlwNVBC32eMbRbZyVF2aw2zn+dSIRrFsgh4t73n8bNFUkhoa0WTw94+wGKsyNfzNDDNUqok0BGNfMVbyeL20MIBOJHdhdsrocIKP68Y9L3GHjfMadADGGdH2nsSg6DbgNdp76TsgJqqshHnJ9c6qV+5kezuPLnMJtQtf8wMojzWVLCHE/3AbW9RS7A+Kifmj7I6WAlO/FroeC6zZ9rvg1IVuoFAuMMLlKffdrjVVrNnckFoW02QQr5BE/E5tAXRQEQeY8s/OCinNJbTP0VeCaeTZnf2do2Te8h8kB6MHAS+X/R6n3mc10/RkNigvkC1bWWSZB3PJ4mmiGRxFp7WypwyXM6gD4LRiE8aBHWaY9Lp1Y8MrP+9gmLIvzRqO2RGW8+F1sCSWXBwCAmZgN/rON9/qEeJ7lSl81sPfegxOm7X5v1B1CBDcdpud6RRvTiGtkOdk/kYdWkdToBP7VK5SA1uDxrKSztrek9lxmaS++RKYp2uS+7neW+p5MKisCyRFaIS4h6TtmPD0xVDVER93fPYdG1aNGrG4P7FRON8wEZQG4qbI1zISpIHo6pCrUMerI3nhLgDQB7+7wWpBp83f/fiGFEbptmsqN1e2+5HUvkDbMTM0RcWQQoABXGn3K0SIG3WqZS3m/KOCYtS4SL8m7yOJc0fAAd5FdGuWQPFLnY2WkDVpXt74MGuEB+jjLbYLMAi/+1g==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ghcr-cred
      namespace: flux-system
    type: kubernetes.io/dockerconfigjson
