apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-cred
  namespace: flux-system
spec:
  encryptedData:
    .dockerconfigjson: AgBlMekzJ/EeZQh+76Qkjq2SpYGkFMHmMKwt16aLLeTGzcAoAmt8jzpiHcaM6LFo+GGFQInrpIs3dTzp/VSr3EChM68kems1Ypb5gpLms/gBkSY2PQj2s42nD3Q86vy2IPKqq+Z33HLHKrwx6HOwn31jN150LePDALEx0ANNnECraaAkJlDtj2Z7rDSzrl/s8w17t9DhowJwQPsExWAgYaB5icQ2DA5m/UygfDUw5+LkMFsuY109O4ppsvCo5Dz4F8qx0TVsSloVfwKoXIVpMgAOvYl1axXktsmxcD0dCxgLLIofJyS9h/OCHIrVDT6LDWk367FR+t+ZE4Y6vilZFgrywqT9MdyVcpFwLTkw4Kixn/eOzudAgrazlpEud3t282LfAfxTlXGOdKGW2RXGr/c76Ue8Puef+0ZU/P2X08U3llBhj8iMBgrQDyTJf/6i+KolBvT5Jme+6hPFkQaWhD67bLrrkUPuq6aJN3i43OuVbupD3eALKzd+1D6xqSlu3TQevFB7FcyIEsSp5eEVvhzhV4IagDDl2D/N37azg4IPXsn6HdJ2jcyXyM7VZisCbY7KoWGuKe8TgEq1VAglAwiiCcs6vANhmAmdF18v94RPYCbsJxu4C8V4dKZvprUZ20ainO8cJ0Uu/H1DYLZ6w0joc+Hh24xKv6HbOdyPS64OtZYGf1a6vLg70L9NnqpqTrq8WLh0nJG7wU1fD3v8gSxl+Sd3wvfYCrTA3jl3K+A7EZBetGwJ5FpcZ/h6KGk3nPqQ+6pM8UlUsUD7oSsj3MSegjqfZc9quISMxtgTENSxux3EsBNqt6Sgi9Bg7WCtyYchDOJi23t6jv4U/cmNF8+5fC/pg+JK9r9mlZzlcrb+ogUIPS9yHxfGvZDoK9vHkIasiWZbTLw1KScVSkbjKkEHGDaOTP7g7z/Z/SEqqPuJ6XJ6nL695PQ7WBKs1VMSIxKAN3ZxEcpM08uBZbzrGCrGIpwkTa/6s2WyywVOVbWn9it8INraUg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ghcr-cred
      namespace: flux-system
    type: kubernetes.io/dockerconfigjson

